<template>
<div>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="#" @click="changeSelected('')">Monjosh</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      
      <li id="navCajero" @click="changeSelected('Cajero')" :class="['nav-item', {active : selected === 'Cajero'}]">
        <a class="nav-link" href="#">Cashier</a>
      </li>
      <li id="navChef" @click="changeSelected('Chef')" :class="['nav-item', {active : selected === 'Chef'}]">
        <a class="nav-link" href="#">Chef</a>
      </li>
    </ul>
    
  </div>
</nav>

<transition name="fade">
  <div class="bg-pan-right gradient-hor flex-center" v-if="selected === ''" >
    <div class="container">
      <div class="row">
        <div class="col-sm border-right" @click="changeSelected('Cajero')"  >
          <i class="fas fa-cash-register fa-10x"></i>
        </div>
        <div class="col-sm" @click="changeSelected('Chef')">
          <img  src="chef.png" style="width:150px;height:150px;">
        </div>
      </div>
      <div class="row">
        <div class="col-sm border-right" @click="changeSelected('Cajero')" >
          <h1>I'm a Cashier</h1>
        </div>
        <div class="col-sm" @click="changeSelected('Chef')">
          <h1>I'm a Chef</h1>
        </div>
      </div>
    </div> 
  </div>
</transition>
</div>
</template>

<script>

import Home  from '../Home.vue'

export default {
  name: 'Menu',
  props:{

  },
  data(){
    return{
      selected: ''
    }
  },
  methods: {
    changeSelected(vista){
      this.selected = vista;
      this.$emit('selected', this.selected);
    }
  }
}

</script>

<style scoped>
.round {
  border-radius: 25px;
  border: 2px solid #73AD21;
  padding: 20px;
  width: 200px;
  height: 150px;
}

.flex-center {
  display: -webkit-box;
  display: flex;
  -webkit-box-align: center;
          align-items: center;
  -webkit-box-pack: center;
          justify-content: center;
}
/* This is our background gradient layer */
.gradient-hor {
  position: absolute;
  width: 100%;
  height: 100%;
  overflow: hidden;
  top: 0;
  left: 0;
  /* Note that the bg width is set to 600%!!! */
  background-size: 600% 100%;
  background-image: -webkit-gradient(linear, right top, left top, from(#2dcca7), color-stop(#3e91cc), to(#cc6aa5));
  background-image: linear-gradient(270deg, #2dcca7, #3e91cc, #cc6aa5);
}
/* Animista animation helper class */
.bg-pan-right {
  -webkit-animation: bg-pan-right 6s both;
          animation: bg-pan-right 6s both;
}
/* ----------------------------------------------
 * Generated by Animista on 2020-1-15 18:47:44
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */
/**
 * ----------------------------------------
 * animation bg-pan-right
 * ----------------------------------------
 */
@-webkit-keyframes bg-pan-right {
  0% {
    background-position: 0% 50%;
  }
  100% {
    background-position: 100% 50%;
  }
}
@keyframes bg-pan-right {
  0% {
    background-position: 0% 50%;
  }
  100% {
    background-position: 100% 50%;
  }
}

.fade-enter{
  opacity: 0;
}

.fade-enter-active{
  transition: opacity 1s;
}

.fade-leave{
  /* opacity: 1; */
}

.fade-leave-active{
  transition: opacity 1s;
  opacity: 0;
}


</style>