<template>
  <div class="eclipse-container">
    <div class="eclipse">
      <div></div>
    </div>
  </div>
</template>

<style scoped>

@keyframes eclipse {
  0% { transform: rotate(0deg) }
  50% { transform: rotate(180deg) }
  100% { transform: rotate(360deg) }
}
.eclipse div {
  position: absolute;
  animation: eclipse 0.5s linear infinite;
  width: 160px;
  height: 160px;
  top: 20px;
  left: 20px;
  border-radius: 50%;
  box-shadow: 0 4px 0 0 #985d4e;
  transform-origin: 80px 82px;
}
.eclipse-container {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: white;
}
.eclipse {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.eclipse div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>
