<template>
  <div class="bg-pan-right gradient-hor flex-center">
    <div class="container">
      <div class="row">
        <div class="col-sm border-right">
          <i class="fas fa-cash-register fa-10x"></i>
          <h1>I'm a Cashier</h1>
        </div>
        <div class="col-sm">
          <img  src="chef.png" style="width:180px;height:180px;">
          <h1>I'm a Chef</h1>
        </div>
      </div>
      <div class="row">
        <div class="col-sm border-right">
          <h1>I'm a Cashier</h1>
        </div>
        <div class="col-sm">
          <h1>I'm a Chef</h1>
        </div>
      </div>
    </div> 
  </div>
</template>

<script>
import axios from 'axios';


export default {
  name: 'Home',
  data() {
    return {
      msg: 'Hello!',
    };
  },
  methods:{

  }
};
</script>

<style scoped>
.round {
  border-radius: 25px;
  border: 2px solid #73AD21;
  padding: 20px;
  width: 200px;
  height: 150px;
}

.flex-center {
  display: -webkit-box;
  display: flex;
  -webkit-box-align: center;
          align-items: center;
  -webkit-box-pack: center;
          justify-content: center;
}
/* This is our background gradient layer */
.gradient-hor {
  position: absolute;
  width: 100%;
  height: 100%;
  overflow: hidden;
  top: 0;
  left: 0;
  /* Note that the bg width is set to 600%!!! */
  background-size: 600% 100%;
  background-image: -webkit-gradient(linear, right top, left top, from(#2dcca7), color-stop(#3e91cc), to(#cc6aa5));
  background-image: linear-gradient(270deg, #2dcca7, #3e91cc, #cc6aa5);
}
/* Animista animation helper class */
.bg-pan-right {
  -webkit-animation: bg-pan-right 6s both;
          animation: bg-pan-right 6s both;
}
/* ----------------------------------------------
 * Generated by Animista on 2020-1-15 18:47:44
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */
/**
 * ----------------------------------------
 * animation bg-pan-right
 * ----------------------------------------
 */
@-webkit-keyframes bg-pan-right {
  0% {
    background-position: 0% 50%;
  }
  100% {
    background-position: 100% 50%;
  }
}
@keyframes bg-pan-right {
  0% {
    background-position: 0% 50%;
  }
  100% {
    background-position: 100% 50%;
  }
}

</style>